In [9]:
import torch
from transformers import AutoTokenizer

In [29]:
tokenizer = AutoTokenizer.from_pretrained("/Users/yousx/models/llama_tokenizers")

In [35]:
tokenizer.add_bos_token=False
tokenizer.add_eos_token=True

In [36]:
tokenizer.encode("abc")

[25638, 2]

In [27]:
def pad_right(x, pad_id):
        # pad right based on the longest sequence
        n = max_len - len(x)
        return torch.cat((x, torch.full((n,), pad_id, dtype=x.dtype)))

In [7]:
micro_batch_size = 4

In [25]:
ix = torch.randint(len(data), (micro_batch_size,))
ix

tensor([9, 9, 9, 1])

In [24]:
input_ids = [data[i].type(torch.int64) for i in ix]
input_ids

[tensor([51, 52, 53, 54, 55, 56, 57, 58, 59, 60]),
 tensor([81, 82, 83, 84, 85, 86, 87, 88, 89, 90]),
 tensor([41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 tensor([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])]

In [28]:
x = torch.stack([pad_right(x, pad_id=0) for x in input_ids])


tensor([[51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
        [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [23]:
max_len = max(len(s) for s in input_ids)
max_len

10